In [7]:
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import numpy as np

In [2]:
market_seoul= pd.read_csv('소상공인시장진흥공단_상가(상권)정보_서울_202303.csv')
market_seoul[:3]

C:\Users\hi-sinchon\AppData\Local\Temp\ipykernel_664\3495024417.py:1: DtypeWarning: Columns (2) have mixed types. Specify dtype option on import or set low_memory=False.
  market_seoul= pd.read_csv('소상공인시장진흥공단_상가(상권)정보_서울_202303.csv')

,상가업소번호,상호명,지점명,상권업종대분류코드,상권업종대분류명,상권업종중분류코드,상권업종중분류명,상권업종소분류코드,상권업종소분류명,표준산업분류코드,...,건물관리번호,건물명,도로명주소,구우편번호,신우편번호,동정보,층정보,호정보,경도,위도
0,MA0101202210A0037544,영자's곱창,NaN,I2,음식,I201,한식,I20109,곱창 전골/구이,I56111,...,1121510100101690021003140,NaN,서울특별시 광진구 면목로 172,143900,4904,NaN,1,NaN,127.082832,37.568503
1,MA0101202210A0097916,호텔클로이,NaN,I1,숙박,I101,일반 숙박,I10102,여관/모텔,I55102,...,1114014500101300000014092,유성장,서울특별시 중구 을지로42길 11,100411,4561,NaN,NaN,NaN,127.005849,37.565708
2,MA0101202210A0096343,나라차중계태권도장,NaN,P1,교육,P106,기타 교육,P10601,태권도/무술학원,P85611,...,1135010600103640019010971,삼부프라자,서울특별시 노원구 한글비석로 242,139861,1734,NaN,NaN,NaN,127.076956,37.649226

In [3]:
market_seoul.columns

Index(['상가업소번호', '상호명', '지점명', '상권업종대분류코드', '상권업종대분류명', '상권업종중분류코드',
       '상권업종중분류명', '상권업종소분류코드', '상권업종소분류명', '표준산업분류코드', '표준산업분류명', '시도코드',
       '시도명', '시군구코드', '시군구명', '행정동코드', '행정동명', '법정동코드', '법정동명', '지번코드',
       '대지구분코드', '대지구분명', '지번본번지', '지번부번지', '지번주소', '도로명코드', '도로명', '건물본번지',
       '건물부번지', '건물관리번호', '건물명', '도로명주소', '구우편번호', '신우편번호', '동정보', '층정보',
       '호정보', '경도', '위도'],
      dtype='object')

In [ ]:
# 삭제할 컬럼
# 상가업소번호, 지점명, 상권업종대분류코드, 상권업종중분류코드,상권업종소분류코드,표준산업분류코드,시도코드
# 시군구코드, 행정동코드 ,법정동코드,지번코드,대지구분코드,대지구분명,'지번본번지', '지번부번지', '지번주소', '도로명코드', '도로명', '건물본번지',
# '건물부번지', '건물관리번호', '건물명', '도로명주소', '구우편번호', '신우편번호', '동정보', '층정보',
# '호정보', '경도', '위도','법정동명'

In [4]:
# 컬럼 삭제
market_seoul.drop(columns=['상가업소번호','지점명','상권업종대분류코드','상권업종중분류코드','상권업종소분류코드','표준산업분류코드','시도코드','시군구코드','행정동코드','법정동코드','지번코드','대지구분코드','대지구분명','지번본번지', '지번부번지', '지번주소', '도로명코드', '도로명', '건물본번지','건물부번지', '건물관리번호', '건물명', '도로명주소', '구우편번호', '신우편번호', '동정보', '층정보','호정보', '경도', '위도','법정동명'],inplace=True)

In [6]:
market_seoul[:10]

         상호명 상권업종대분류명   상권업종중분류명  상권업종소분류명          표준산업분류명    시도명  시군구명  행정동명
0     영자's곱창       음식         한식  곱창 전골/구이       한식 일반 음식점업  서울특별시   광진구  중곡3동
1      호텔클로이       숙박      일반 숙박     여관/모텔              여관업  서울특별시    중구   광희동
2  나라차중계태권도장       교육      기타 교육  태권도/무술학원    태권도 및 무술 교육기관  서울특별시   노원구  중계본동
3      이상한스냅    과학·기술      사진 촬영     사진촬영업           사진 처리업  서울특별시   양천구  신월5동
4        토끼정       음식         한식    백반/한정식       한식 일반 음식점업  서울특별시   강서구  가양1동
5   스쿨푸드딜리버리       음식      기타 간이  김밥/만두/분식  김밥 및 기타 간이 음식점업  서울특별시   강북구  수유3동
6        가배차       음식         한식    백반/한정식       한식 일반 음식점업  서울특별시   송파구  송파1동
7   비에이치씨항동점       음식      기타 간이        치킨           치킨 전문점  서울특별시   구로구    항동
8    무지개삼성약국       소매  의약·화장품 소매        약국   의약품 및 의료용품 소매업  서울특별시   강남구  일원1동
9       와우랩핑    과학·기술         광고    광고 대행업           광고 대행업  서울특별시  영등포구  신길1동

In [8]:
# 정보 확인
market_seoul.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 474260 entries, 0 to 474259
Data columns (total 8 columns):
 #   Column    Non-Null Count   Dtype
---  ------    --------------   -----
 0   상호명       474260 non-null  object
 1   상권업종대분류명  474260 non-null  object
 2   상권업종중분류명  474260 non-null  object
 3   상권업종소분류명  474260 non-null  object
 4   표준산업분류명   474260 non-null  object
 5   시도명       474260 non-null  object
 6   시군구명      474260 non-null  object
 7   행정동명      474260 non-null  object
dtypes: object(8)
memory usage: 28.9+ MB

In [10]:
# 결측치 확인
market_seoul.isna().sum()

상호명         0
상권업종대분류명    0
상권업종중분류명    0
상권업종소분류명    0
표준산업분류명     0
시도명         0
시군구명        0
행정동명        0
dtype: int64

In [11]:
# 모든 행이 결측치인 행 제거 -> 없음
market_seoul.dropna(axis=0, how='all')

,상호명,상권업종대분류명,상권업종중분류명,상권업종소분류명,표준산업분류명,시도명,시군구명,행정동명
0,영자's곱창,음식,한식,곱창 전골/구이,한식 일반 음식점업,서울특별시,광진구,중곡3동
1,호텔클로이,숙박,일반 숙박,여관/모텔,여관업,서울특별시,중구,광희동
2,나라차중계태권도장,교육,기타 교육,태권도/무술학원,태권도 및 무술 교육기관,서울특별시,노원구,중계본동
3,이상한스냅,과학·기술,사진 촬영,사진촬영업,사진 처리업,서울특별시,양천구,신월5동
4,토끼정,음식,한식,백반/한정식,한식 일반 음식점업,서울특별시,강서구,가양1동
...,...,...,...,...,...,...,...,...
474255,행복한부동산중개사무소,부동산,부동산 서비스,부동산 중개/대리업,부동산 중개 및 대리업,서울특별시,양천구,신월3동
474256,좋은소식법률사무소,과학·기술,법무관련,변호사,변호사업,서울특별시,광진구,화양동
474257,루젤라,음식,서양식,경양식,서양식 음식점업,서울특별시,강남구,논현2동
474258,153커피,수리·개인,가전제품 수리,가전제품 수리업,가전제품 수리업,서울특별시,영등포구,양평2동
474259,송죽상회,소매,식료품 소매,건어물/젓갈 소매업,건어물 및 젓갈류 소매업,서울특별시,중구,을지로동

In [12]:
# csv 파일로 저장
market_seoul.to_csv('market_seoul.csv',encoding='utf-8',index=False)